export enum Status {
  NEW = "NEW",
  IN_PROGRESS = "IN_PROGRESS",
  SHIPPED = "SHIPPED",
  RETURNED = "RETURNED",
  IN_BACKORDER = "IN_BACKORDER",
  MANCO = "MANCO",
  CANCELED = "CANCELED",
  IN_COMBI = "IN_COMBI",
  CLOSED = "CLOSED",
  REQUIRES_CORRECTION = "REQUIRES_CORRECTION",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
}
